name: bloc_lint
description: Official lint rules for development when using the bloc state management library.
version: 0.2.0-dev.0
repository: https://github.com/felangel/bloc/tree/master/packages/bloc_lint
issue_tracker: https://github.com/felangel/bloc/issues
homepage: https://github.com/felangel/bloc
documentation: https://bloclibrary.dev
topics: [bloc, state-management, lint]
funding: [https://github.com/sponsors/felangel]

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  analyzer: ^7.0.0
  shelf: ^1.0.0
  shelf_router: ^1.1.4

screenshots:
  - description: The bloc_lint package logo.
    path: screenshots/logo.png
